### ISSUE TITLE
Werk dat nog gedaan moet worden

### ISSUE THREAD

**Issue by YouryDW** [YouryDW/GroepTQuiz2014#37]
- [x] Opslaan van gegevens
 - [x] Naar TXT-bestand (@tonyleekens) zie #38
 - [x] Naar embedded DB (@yourydw) zie #39 
- [x] Lezen van gegevens
 - [x] Van TXT-bestand (@tonyleekens) zie #40 
 - [x] Van embedded DB (@yourydw) zie #41
- [x] Views aanmaken
 - [x] Opdrachten beheren (@yourydw) zie #42
  + Lijst weergeven
  + Nieuw knop naar Opdracht aanmaken/editeren View
  + Edit knop naar Opdracht aanmaken/editeren View
  + Verwijder knop
 - [x] Opdracht aanmaken/editeren (???) zie #43
  + Controls aanmaken
 - [x] Quizen beheren (@yourydw) zie #44
  + Lijst weergeven
  + Nieuw knop naar Quiz aanmaken/editeren View
  + Edit knop naar Quiz aanmaken/editeren View
  + Verwijder knop
 - [x] Quiz aanmaken/editeren (???) zie #45
  + Controls aanmaken
- [x] Controllers aanmaken
 - [x] Opdrachten beheren (@yourydw) zie #46
  + Hoofdmenu
  + Nieuwe opdracht
  + Wijzig opdracht
  + Verwijder opdracht
 - [x] Opdracht aanmaken/editeren (???) zie #47
  + Opslaan
  + Annuleren
 - [x] Quizen beheren (???) zie #48
  + Hoofdmenu
  + Nieuwe quiz
  + Wijzig quiz
  + Verwijder quiz
 - [x] Quiz aanmaken/editeren (???) zie #49
  + Opslaan
  + Annuleren
